#####################################################################
# Copyright (C) 2024 HIDDEN UNIVERSITY
# HIDDEN WEBSITE
# HIDDEN SUBTEXT
# HIDDEN INSTITUTE
# 
# Authors: AUTHORS CURRENTLY HIDDEN DUE TO ONGOING PEER REVIEW PROCESS
# 
# Licensed under the MIT License (the "License");
# you may only use this file in compliance with the License.
# You may obtain a copy of the License at
# 
#         https://mit-license.org/
# 
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
####################################################################


renaming_convention_dict = {    
    "timestamp": "timestamp",
    "frame_number": "groundtruth+frame_number+",
    "face_x": "head+face_x+pose",
    "face_y": "head+face_y+pose",
    "face_width": "head+face_width+state",
    "face_height": "head+face_height+state",
    "face_confidence": "head+face_confidence+state",
    "face_quat_w": "head+face_quat_w+pose",
    "face_quat_x": "head+face_quat_x+pose",
    "face_quat_y": "head+face_quat_y+pose",
    "face_quat_z": "head+face_quat_z+pose",
    "face_trans_x": "head+face_trans_x+pose",
    "face_trans_y": "head+face_trans_y+pose",
    "face_trans_z": "head+face_trans_z+pose",
    "face_yaw": "head+face_yaw+pose",
    "face_pitch": "head+face_pitch+pose",
    "face_roll": "head+face_roll+pose",
    "mideye_origin_x": "head+mideye_origin_x+pose",
    "mideye_origin_y": "head+mideye_origin_y+pose",
    "mideye_origin_z": "head+mideye_origin_z+pose",
    "mideye_origin_confidence": "head+mideye_origin_confidence+state",
    "gaze_direction_x": "gaze+gaze_direction_x+pose",
    "gaze_direction_y": "gaze+gaze_direction_y+pose",
    "gaze_direction_z": "gaze+gaze_direction_z+pose",
    "gaze_direction_confidence": "gaze+gaze_direction_confidence+state",
    "gaze_direction_source": "gaze+gaze_direction_source+state",
    "target_zone": "aoi+target_zone+",
    "left_eye_opening_mm": "eye+left_eye_opening_mm+",
    "left_eye_opening_percent": "eye+left_eye_opening_percent+",
    "left_eye_confidence": "eye+left_eye_confidence+",
    "left_eye_state": "eye+left_eye_state+",
    "right_eye_opening_mm": "eye+right_eye_opening_mm+",
    "right_eye_opening_percent": "eye+right_eye_opening_percent+",
    "right_eye_confidence": "eye+right_eye_confidence+",
    "right_eye_state": "eye+right_eye_state+",
    "drowsiness": "misc+drowsiness+",
    "drowsinessTime_ms": "misc+drowsinessTime_ms+",
    "inattention": "misc+inattention+",
    "inattentionTime_ms": "misc+inattentionTime_ms+",
    "accumulatedInattention": "misc+accumulatedInattention+",
    "accumulatedInattentionTime_ms": "misc+accumulatedInattentionTime_ms+",
    "LeftEyeOutercorner_V1_x": "head+LeftEyeOutercorner_V1_x+pose",
    "LeftEyeOutercorner_V1_y": "head+LeftEyeOutercorner_V1_y+pose",
    "LeftEyeOutercorner_V1_attribute": "head+LeftEyeOutercorner_V1_attribute+state",
    "LeftEyeInnercorner_V1_x": "head+LeftEyeInnercorner_V1_x+pose",
    "LeftEyeInnercorner_V1_y": "head+LeftEyeInnercorner_V1_y+pose",
    "LeftEyeInnercorner_V1_attribute": "head+LeftEyeInnercorner_V1_attribute+state",
    "RightEyeOutercorner_V1_x": "head+RightEyeOutercorner_V1_x+pose",
    "RightEyeOutercorner_V1_y": "head+RightEyeOutercorner_V1_y+pose",
    "RightEyeOutercorner_V1_attribute": "head+RightEyeOutercorner_V1_attribute+state",
    "RightEyeInnercorner_V1_x": "head+RightEyeInnercorner_V1_x+pose",
    "RightEyeInnercorner_V1_y": "head+RightEyeInnercorner_V1_y+pose",
    "RightEyeInnercorner_V1_attribute": "head+RightEyeInnercorner_V1_attribute+state",
    "LeftMouthcorner_V1_x": "head+LeftMouthcorner_V1_x+pose",
    "LeftMouthcorner_V1_y": "head+LeftMouthcorner_V1_y+pose",
    "LeftMouthcorner_V1_attribute": "head+LeftMouthcorner_V1_attribute+state",
    "RightMouthcorner_V1_x": "head+RightMouthcorner_V1_x+pose",
    "RightMouthcorner_V1_y": "head+RightMouthcorner_V1_y+pose",
    "RightMouthcorner_V1_attribute": "head+RightMouthcorner_V1_attribute+state",
    "LeftNostrilSill_V1_x": "head+LeftNostrilSill_V1_x+pose",
    "LeftNostrilSill_V1_y": "head+LeftNostrilSill_V1_y+pose",
    "LeftNostrilSill_V1_attribute": "head+LeftNostrilSill_V1_attribute+state",
    "RightNostrilSill_V1_x": "head+RightNostrilSill_V1_x+pose",
    "RightNostrilSill_V1_y": "head+RightNostrilSill_V1_y+pose",
    "RightNostrilSill_V1_attribute": "head+RightNostrilSill_V1_attribute+state",
    "BAC": "groundtruth+BAC+",
    "no_gaze_available": "aoi+no_gaze_available+",
    "driver_side_windscreen": "aoi+driver_side_windscreen+",
    "copilot_side_windscreen": "aoi+copilot_side_windscreen+",
    "left_rear_mirror": "aoi+left_rear_mirror+",
    "right_rear_mirror": "aoi+right_rear_mirror+",
    "left_window": "aoi+left_window+",
    "right_window": "aoi+right_window+",
    "central_rear_mirror": "aoi+central_rear_mirror+",
    "driver_instruments": "aoi+driver_instruments+",
    "navigation_display": "aoi+navigation_display+",
    "middle_instrument_cluster": "aoi+middle_instrument_cluster+",
    "no_target_zone_detected": "aoi+no_target_zone_detected+",
    "roll": "head+roll+pose",
    "pitch": "head+pitch+pose",
    "yaw": "head+yaw+pose",
    "target_zone_changes_1000": "aoi+target_zone_changes_1000+",
    "azimuth": "gaze+azimuth+pose",
    "elevation": "gaze+elevation+pose",
    "eye_movement_type": "event+eye_movement_type+eventspec",
    "eye_movement_peak_vel": "event+eye_movement_peak_vel+eventspec",
    "eye_movement_avg_vel": "event+eye_movement_avg_vel+eventspec",
    "eye_movement_med_vel": "event+eye_movement_med_vel+eventspec",
    "eye_movement_amp_given": "event+eye_movement_amp_given+eventspec",
    "eye_movement_amp_calc": "event+eye_movement_amp_calc+eventspec",
    "eye_movement_duration": "event+eye_movement_duration+eventspec",
    "FIXA": "event+FIXA+onehot",
    "HPSO": "event+HPSO+onehot",
    "IHPS": "event+IHPS+onehot",
    "ILPS": "event+ILPS+onehot",
    "ISAC": "event+ISAC+onehot",
    "LPSO": "event+LPSO+onehot",
    "MISSING": "event+MISSING+onehot",
    "PURS": "event+PURS+onehot",
    "SACC": "event+SACC+onehot",
    "velocity": "gaze+gaze+velocity",
    "velocity_azimuth": "gaze+azimuth+velocity",
    "velocity_elevation": "gaze+elevation+velocity",
    "angle_change": "gaze+angle_change+velocity",
    "angle_change_azimuth": "gaze+angle_change_azimuth+velocity",
    "angle_change_elevation": "gaze+angle_change_elevation+velocity",
    "direction": "gaze+direction+velocity",
    "velocity_roll": "head+roll+velocity",
    "velocity_pitch": "head+pitch+velocity",
    "velocity_yaw": "head+yaw+velocity",
    "velocity_head": "head+head+velocity",
    "velocity_mideye_origin": "head+mideye_origin+velocity",
    "velocity_mideye_origin_x": "head+mideye_origin_x+velocity",
    "velocity_mideye_origin_y": "head+mideye_origin_y+velocity",
    "velocity_mideye_origin_z": "head+mideye_origin_z+velocity",
    "acceleration": "gaze+gaze+acceleration",
    "acceleration_r": "gaze+_r+acceleration",
    "acceleration_azimuth": "gaze+azimuth+acceleration",
    "acceleration_elevation": "gaze+elevation+acceleration",
    "acceleration_azimuth_elevation": "gaze+azimuth_elevation+acceleration",
    "acceleration_roll": "head+roll+acceleration",
    "acceleration_pitch": "head+pitch+acceleration",
    "acceleration_yaw": "head+yaw+acceleration",
    "acceleration_head": "head+head+acceleration",
    "acceleration_mideye_origin": "head+mideye_origin+acceleration",
    "acceleration_mideye_origin_x": "head+mideye_origin_x+acceleration",
    "acceleration_mideye_origin_y": "head+mideye_origin_y+acceleration",
    "acceleration_mideye_origin_z": "head+mideye_origin_z+acceleration",
    "jerk": "gaze+gaze+jerk",
    "jerk_r": "gaze+r+jerk",
    "jerk_azimuth": "gaze+azimuth+jerk",
    "jerk_elevation": "gaze+elevation+jerk",
    "jerk_azimuth_elevation": "gaze+azimuth_elevation+jerk",
    "jerk_roll": "head+roll+jerk",
    "jerk_pitch": "head+pitch+jerk",
    "jerk_yaw": "head+yaw+jerk",
    "jerk_head": "head+head+jerk",
    "jerk_mideye_origin": "head+mideye_origin+jerk",
    "jerk_mideye_origin_x": "head+mideye_origin_x+jerk",
    "jerk_mideye_origin_y": "head+mideye_origin_y+jerk",
    "jerk_mideye_origin_z": "head+mideye_origin_z+jerk",
    "snap": "gaze+gaze+snap",
    "snap_r": "gaze+r+snap",
    "snap_azimuth": "gaze+azimuth+snap",
    "snap_elevation": "gaze+elevation+snap",
    "snap_azimuth_elevation": "gaze+azimuth_elevation+snap",
    "snap_roll": "head+roll+snap",
    "snap_pitch": "head+pitch+snap",
    "snap_yaw": "head+yaw+snap",
    "snap_head": "head+head+snap",
    "snap_mideye_origin": "head+mideye_origin+snap",
    "snap_mideye_origin_x": "head+mideye_origin_x+snap",
    "snap_mideye_origin_y": "head+mideye_origin_y+snap",
    "snap_mideye_origin_z": "head+mideye_origin_z+snap",
    "intersections_x_622": "gaze+intersections_x_622+pose",
    "intersections_y_622": "gaze+intersections_y_622+pose",
    "intersections_x_1122": "gaze+intersections_x_1122+pose",
    "intersections_y_1122": "gaze+intersections_y_11221+pose",
    "phase": "groundtruth+phase+",
    "scenario": "groundtruth+scenario+",
    "variant": "groundtruth+variant+",
}